package com.jammking.loopbox.domain.exception



enum class ErrorCode {

    // --- Not found ---
    PROJECT_NOT_FOUND,
    MUSIC_NOT_FOUND,
    IMAGE_NOT_FOUND,
    VERSION_NOT_FOUND,
    TASK_NOT_FOUND,
    RESOURCE_NOT_FOUND,

    // --- Inconsistent state ---
    INCONSISTENT_PROJECT_MUSIC_RELATION,
    INCONSISTENT_PROJECT_IMAGE_RELATION,
    INCONSISTENT_MUSIC_TASK_RELATION,
    INCONSISTENT_IMAGE_TASK_RELATION,

    // --- State violation ---
    INVALID_PROJECT_STATE,
    INVALID_MUSIC_STATE,
    INVALID_MUSIC_VERSION_STATE,
    INVALID_IMAGE_STATE,
    INVALID_IMAGE_VERSION_STATE,
    INVALID_TASK_STATE,
    DUPLICATE_PROJECT_ID,
    DUPLICATE_MUSIC_ID,
    DUPLICATE_VERSION_ID,

    // --- Validation ---
    INVALID_PROJECT_TITLE,
    INVALID_MUSIC_AI_PROVIDER,
    INVALID_IMAGE_AI_PROVIDER,
    INVALID_AUDIO_FILE_PATH,
    INVALID_IMAGE_FILE_PATH,

    // --- Fallback ---
    INTERNAL_SERVER_ERROR
}
